{
  "version": "0.0.1",
  "steps": [
    {
      "tag": "create_migration",
      "name": "create initial migration",
      "filepath": "prisma/migrations/20250815140000_init/migration.sql",
      "content": "-- CreateTable\nCREATE TABLE \"User\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n    \"name\" TEXT,\n    \"email\" TEXT NOT NULL,\n    \"password\" TEXT NOT NULL,\n    \"role\" TEXT NOT NULL DEFAULT 'USER',\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL\n);\n\n-- CreateTable\nCREATE TABLE \"Partner\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n    \"name\" TEXT NOT NULL,\n    \"imageUrl\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL\n);\n\n-- CreateTable\nCREATE TABLE \"Product\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n    \"title\" TEXT NOT NULL,\n    \"price\" DOUBLE PRECISION NOT NULL,\n    \"currency_id\" TEXT NOT NULL,\n    \"thumbnail\" TEXT NOT NULL,\n    \"condition\" TEXT NOT NULL,\n    \"available_quantity\" INTEGER NOT NULL,\n    \"seller_nickname\" TEXT NOT NULL,\n    \"permalink\" TEXT NOT NULL,\n    \"categoryId\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    CONSTRAINT \"Product_categoryId_fkey\" FOREIGN KEY (\"categoryId\") REFERENCES \"Category\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE\n);\n\n-- CreateTable\nCREATE TABLE \"Category\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n    \"name\" TEXT NOT NULL\n);\n\n-- CreateTable\nCREATE TABLE \"Picture\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n    \"url\" TEXT NOT NULL,\n    \"productId\" TEXT NOT NULL,\n    CONSTRAINT \"Picture_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"Product\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE\n);\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"User_email_key\" ON \"User\"(\"email\");\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"Product_permalink_key\" ON \"Product\"(\"permalink\");\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"Category_name_key\" ON \"Category\"(\"name\");"
    }
  ]
}